#!/usr/bin/env bash
set -euo pipefail

# Helper script to guide you through exporting from production
# This doesn't do the export itself, but helps you prepare

echo "=== WordPress Export Helper ==="
echo ""
echo "This script helps you prepare to export from gaycarboys.com"
echo ""

# Check if we're in the right directory
if [[ ! -f "docker-compose.yml" ]]; then
  echo "❌ Error: Run this from the project root (where docker-compose.yml is)"
  exit 1
fi

echo "What type of hosting is gaycarboys.com on?"
echo ""
echo "1) WordPress.com (managed hosting - limited export)"
echo "2) Self-hosted WordPress (SSH access)"
echo "3) Self-hosted WordPress (cPanel / hosting control panel)"
echo "4) Self-hosted WordPress (FTP/SFTP only)"
echo "5) Self-hosted WordPress (WordPress admin / plugin method)"
echo "6) Not sure / need to check"
echo ""
read -p "Enter choice (1-6): " access_type

case $access_type in
  1)
    echo ""
    echo "=== WordPress.com Export ==="
    echo ""
    echo "WordPress.com offers two export options:"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "OPTION A: Jetpack Backup (RECOMMENDED - Most Complete)"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "If you have Jetpack Backup enabled:"
    echo ""
    echo "EXPORT STEPS:"
    echo "1. Log into WordPress.com: https://wordpress.com"
    echo "2. Go to your site dashboard (gaycarboys.com)"
    echo "3. Navigate to: Jetpack → Backups (or Backup in sidebar)"
    echo "4. Find a recent backup point"
    echo "5. Click 'Download' or 'Export'"
    echo "6. Save the backup file (usually .zip or .tar.gz)"
    echo ""
    echo "IMPORT LOCALLY:"
    echo "   ./scripts/wp-import-jetpack-backup.sh ./jetpack-backup-YYYY-MM-DD.zip"
    echo ""
    echo "WHAT'S INCLUDED:"
    echo "✅ Complete database (all tables, settings, users)"
    echo "✅ Full wp-content (themes, plugins, uploads)"
    echo "✅ All media files"
    echo "✅ Configuration and settings"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "OPTION B: Standard XML Export (Content Only)"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "If Jetpack Backup is not available:"
    echo ""
    echo "EXPORT STEPS:"
    echo "1. Log into WordPress.com: https://wordpress.com"
    echo "2. Go to your site dashboard (gaycarboys.com)"
    echo "3. Navigate to: Tools → Export"
    echo "4. Choose 'All content' (recommended)"
    echo "5. Click 'Download Export File'"
    echo "6. Save the XML file (e.g., gaycarboys-export.xml)"
    echo ""
    echo "IMPORT LOCALLY:"
    echo "   ./scripts/wp-import-from-wordpress-com.sh ./gaycarboys-export.xml"
    echo ""
    echo "LIMITATIONS:"
    echo "- ❌ No theme export (WordPress.com uses their own theme system)"
    echo "- ❌ No plugin export (WordPress.com doesn't allow custom plugins)"
    echo "- ❌ No database access"
    echo "- ✅ Content (posts, pages, comments) can be exported"
    echo "- ⚠️  Media files need to be downloaded separately or fetched during import"
    echo ""
    echo "📖 Full guide: docs/EXPORTING_FROM_WORDPRESS_COM.md"
    ;;
  2)
    echo ""
    echo "=== SSH Export Commands ==="
    echo ""
    echo "1. SSH into the server:"
    echo "   ssh user@gaycarboys.com"
    echo ""
    echo "2. Find WordPress location and DB credentials:"
    echo "   cd /path/to/wordpress  # usually public_html or www"
    echo "   grep DB_ wp-config.php"
    echo ""
    echo "3. Export database:"
    echo "   mysqldump -u DB_USER -p DB_NAME > ~/gaycarboys-export.sql"
    echo ""
    echo "4. Export wp-content:"
    echo "   tar -czf ~/wp-content-backup.tar.gz wp-content/"
    echo ""
    echo "5. On your Mac, download both:"
    echo "   scp user@gaycarboys.com:~/gaycarboys-export.sql ./"
    echo "   scp user@gaycarboys.com:~/wp-content-backup.tar.gz ./"
    echo "   tar -xzf wp-content-backup.tar.gz"
    echo ""
    echo "6. Then import locally:"
    echo "   ./scripts/wp-import-from-prod.sh ./gaycarboys-export.sql ./wp-content"
    ;;
  3)
    echo ""
    echo "=== cPanel Export Steps ==="
    echo ""
    echo "DATABASE:"
    echo "1. Log into cPanel"
    echo "2. Open phpMyAdmin"
    echo "3. Select your WordPress database"
    echo "4. Click 'Export' tab → 'Quick' → 'SQL' → 'Go'"
    echo "5. Save as 'gaycarboys-export.sql'"
    echo ""
    echo "FILES:"
    echo "1. In cPanel, open File Manager"
    echo "2. Navigate to WordPress root (usually public_html)"
    echo "3. Right-click 'wp-content' → Compress → Download"
    echo "4. Extract on your Mac"
    echo ""
    echo "Then import:"
    echo "   ./scripts/wp-import-from-prod.sh ./gaycarboys-export.sql ./wp-content"
    ;;
  4)
    echo ""
    echo "=== FTP Export Steps ==="
    echo ""
    echo "FILES:"
    echo "1. Use FileZilla or similar FTP client"
    echo "2. Connect to gaycarboys.com"
    echo "3. Download the entire 'wp-content' folder"
    echo ""
    echo "DATABASE:"
    echo "You'll need to use phpMyAdmin (see cPanel method) or ask your host"
    echo "for a database dump."
    echo ""
    echo "Then import:"
    echo "   ./scripts/wp-import-from-prod.sh ./gaycarboys-export.sql ./wp-content"
    ;;
  5)
    echo ""
    echo "=== WordPress Plugin Method ==="
    echo ""
    echo "1. Install 'All-in-One WP Migration' plugin in WordPress admin"
    echo "2. Go to All-in-One WP Migration → Export → Export To → File"
    echo "3. Download the .wpress file"
    echo ""
    echo "Note: The .wpress file contains everything. You can:"
    echo "- Use the plugin's import feature in your local WordPress, OR"
    echo "- Extract manually (more complex)"
    echo ""
    echo "Alternatively, use 'UpdraftPlus' to create backups and download"
    echo "the database and files separately."
    ;;
  6)
    echo ""
    echo "=== Need to Check Hosting Type ==="
    echo ""
    echo "Ask your friend (the site owner):"
    echo ""
    echo "1. Is the site on WordPress.com (managed hosting)?"
    echo "   → If YES: Use option 1 (WordPress.com export)"
    echo ""
    echo "2. If self-hosted, what hosting provider? (e.g., Bluehost, SiteGround, etc.)"
    echo "3. What access is available:"
    echo "   - cPanel login URL and credentials"
    echo "   - SSH access (username, host, key/password)"
    echo "   - FTP credentials"
    echo "   - WordPress admin access"
    echo ""
    echo "Once you know, run this script again and choose the appropriate option."
    echo ""
    echo "📖 Guides:"
    echo "   - WordPress.com: docs/EXPORTING_FROM_WORDPRESS_COM.md"
    echo "   - Self-hosted: docs/EXPORTING_FROM_PRODUCTION.md"
    ;;
  *)
    echo "Invalid choice"
    exit 1
    ;;
esac

echo ""
echo "=== Next Steps ==="
echo ""
echo "📖 Full guide: docs/EXPORTING_FROM_PRODUCTION.md"
echo ""
echo "Once you have the files, import with:"
echo "   ./scripts/wp-import-from-prod.sh <db-dump.sql> <wp-content-dir>"
echo ""

